language: php

## Run on container environment
sudo: false
    
php:
  - 5.6
  - 7.0
  - hhvm
  
before_script:
  - composer self-update
  - composer update --prefer-source
  - composer dump-autoload

script:
  - vendor/bin/php-cs-fixer fix src --level=psr2 --dry-run -vv
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
