language: php

## Run on container environment
sudo: false

## Cache composer bits
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    
php:
  - 5.6
  - 7
  - hhvm
  
before_script:
  - composer self-update
  - composer update --prefer-source
  - composer dump-autoload

script:
  - vendor/bin/php-cs-fixer fix src --level=psr2 --dry-run -vv
  - vendor/bin/phpunit --coverage-clover coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  
 